apiVersion: v1
kind: Service
metadata:
  name: travelai-api
  namespace: travelai
  labels:
    app: travelai-api
spec:
  type: ClusterIP
  selector:
    app: travelai-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
